INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO,CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Back-end', 'Aqui vem a descrição', 'java');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Front-end', 'Aqui vem a descrição', 'html');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-1', 'Aqui vem a descrição', 'videos');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-2', 'Aqui vem a descrição', 'videos');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-3', 'Aqui vem a descrição', 'html');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-4', 'Aqui vem a descrição', 'java');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-5', 'Aqui vem a descrição', 'videos');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-6', 'Aqui vem a descrição', 'html');
INSERT INTO TB_SERVICO (ID, TITULO, DESCRICAO, CATEGORIA) VALUES (SERVICO_SEQ.NEXTVAL, 'Titulo-8', 'Aqui vem a descrição', 'videos');